add support for Amazon Linux 2022
The patch adds support for the latest release of Amazon Linux 2022.

Support for AL2 (Amazon Linux 2) is not complete at this time.
AL2 comes with ruby 2.0 and fails the install command:

```
$ sudo lkp install
[...]
ERROR:  Error installing bundler:
	bundler requires Ruby version >= 2.6.0.
```

This can be remediated by installing a newer ruby from sources.

Signed-off-by: Sebastian Pop <spop@amazon.com>
Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>